[package]
name = "dagproxy"
version = "0.1.0"
edition = "2024"

[dependencies]
getopts = "0.2.24"
hyper = "1.7.0"
hyper-util = { version = "0.1.17", features = ["full"] }
ip-in-subnet = "0.1.4"
netaddr2 = "0.10.0"
netwatcher = "0.4.0"
network-interface = "2.0.3"
sspi = "0.16.1"
tokio = { version = "1.47.1", features = ["full"] }
http-body-util = "0.1.3"
anyhow = "1.0.100"
hyper-rustls = "0.27.7"
httparse = "1.10.1"
bytes = "1.10.1"
