#[target.'cfg(windows)']
#runner = "powershell -Command Start-Process -Verb runAs -FilePath"

[env]
WINDIVERT_PATH={ value = "WinDivert-2.2.2-A/x64", relative = true }

#[target.x86_64-pc-windows-msvc]
#rustflags = [
#    "-L", "E:/Nextcloud/Desktop/WinDivert-2.2.2-A/x64",
#]